{% set name = "amazon-sagemaker-hyperpod" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon_sagemaker_hyperpod-{{ version }}.tar.gz
  sha256: c201e5bc07b5f6b361b07b6cae513503263e5e41e20658385adc95ec699cee75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:    
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<4.2
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8
    - jupyter_server >=2.0.1,<3
    - boto3
    - botocore
    - jupyterlab >=4.0,<5

test:
  imports:
    - amazon_sagemaker_hyperpod
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://aws.amazon.com/sagemaker/
  summary: 'Amazon SageMaker Hyperpod Jupyter Extension'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bhadrip
    - bhanderig
